service: express-serverless

provider:
  name: aws
  runtime: nodejs20.x
  stage: dev
  region: ap-northeast-1

functions:
  postScheduled:
    handler: handler.handler
    events:
      - schedule:
          rate: rate(1 minute)
          input:
            message: "Hello, this is a scheduled event!"

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3000
